Add config to add labels to cluster agent
Appdynamics/appdynamics-operator pull request #88
Opened 2021-07-22 06:20 UTC by subhashiyer07

2021-07-26 05:44 UTC, harekal7 commented on pkg/controller/clusteragent/clusteragent_controller.go
> +	labels := map[string]string{"name": "clusterAgent", "clusterAgent_cr": clusterAgent.Name}
Do we have to mention this in the docs as well? That by default we are adding two labels. So that customers won't be surprised seeing the additional labels apart from what they mentioned in Spec.labels

2021-07-26 05:44 UTC, harekal7 approved these changes

2021-07-26 05:47 UTC, subhashiyer07 commented on pkg/controller/clusteragent/clusteragent_controller.go
> +	labels := map[string]string{"name": "clusterAgent", "clusterAgent_cr": clusterAgent.Name}
We could add it to docs. But, not sure if customer will be interested in it

2021-07-26 06:04 UTC, avinashk442 approved these changes

2021-07-26 12:50 UTC, bhumijgupta commented on pkg/controller/clusteragent/clusteragent_controller.go
> +	return labels
Based on this code, the user can also override the default `name` and `clusterAgent_cr` labels from `clusteragent.spec.labels`. Is this an intended feature?

2021-07-26 13:23 UTC, subhashiyer07 commented on pkg/controller/clusteragent/clusteragent_controller.go
> +	return labels
Good point Bhumij. No, it is not intended. But, not sure if customer would change these.

2021-07-26 13:32 UTC, bhumijgupta commented on pkg/controller/clusteragent/clusteragent_controller.go
> +	return labels
If it is not intended, then we should fix it as it is small fix. Customers can try to change these labels maybe intentionally or unintentionally. We should also document that default labels cannot be changed.

2021-07-27 05:38 UTC, harekal7 approved these changes

2021-07-27 06:12 UTC, avinashk442 approved these changes

2021-07-27 06:59 UTC, bhumijgupta requested changes

2021-07-27 06:59 UTC, bhumijgupta commented on pkg/controller/clusteragent/clusteragent_controller.go
> +	return labels
## TLDR; Infinite cluster agent pod created

### Context
According to official kubernetes docs, whenever we create a deployment/replica set the deployment/replicaset controller adds additional label `pod-template-hash` which contains the hash of the deployed pod spec. This is used by replicaset to maintain the number of replicas needed

### Bug
Since we are allowing to add custom labels, if we use a `cluster-agent.yaml` which overrides pod template hash as shown below:
```yaml
apiVersion: appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics
spec:
  appName: "test-labels-manual"
  controllerUrl: [READACTED]
  account: [READACTED]
  # docker image info
  image: [READACTED]
  serviceAccountName: appdynamics-cluster-agent
  labels:
    test-label: "works"
    testLabel2: "should_work"
    appdynamics.com/test-label_3: "should_work_too"
    name: "ignore"
    clusterAgent_cr: "ignore2"
    pod-template-hash: "123"
  ### Uncomment the following line if you need pull secret
  #imagePullSecret: "<your-docker-pull-secret-name>"

```
it will override the pod-template-hash which makes the replica set to create infinite cluster agent pods as it feels there's no pod with label `pod-template-hash` which matches the actual pod spec hash.

## Screenshots
![image](https://user-images.githubusercontent.com/30751793/127109755-a458219e-9384-4132-9be9-6605f8e240cd.png)
![image](https://user-images.githubusercontent.com/30751793/127109887-a0552c1d-306e-4fbb-8b73-aabfc3ccc1e5.png)

cc @avinashk442 @harekal7 @akshitgrover

2021-07-27 07:07 UTC, bhumijgupta commented on pkg/controller/clusteragent/clusteragent_controller.go
> +	return labels
Doc reference: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pod-template-hash-label

2021-07-27 09:13 UTC, bhumijgupta approved these changes
LGTM 🚀

2021-07-27 09:28 UTC, harekal7 approved these changes

2021-07-27 09:28 UTC, merged